# Generated by Django 3.2.25 on 2024-06-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0003_alter_credentials_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='password',
            field=models.CharField(max_length=1000),
        ),
    ]
