# Generated by Django 3.2.25 on 2024-06-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager_app', '0004_alter_credentials_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='password',
            field=models.BinaryField(max_length=1000),
        ),
    ]
