# Generated by Django 3.2.25 on 2024-06-22 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_manager_app', '0005_alter_credentials_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='user',
        ),
        migrations.AddField(
            model_name='website',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
