# Generated by Django 3.2.25 on 2024-06-22 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password_manager_app', '0006_auto_20240623_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='websites', to=settings.AUTH_USER_MODEL),
        ),
    ]
